services:
  - type: web
    name: trendforage-aqp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run aqp/ui_app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    branch: main
